package com.paul.base.sync.oracle.user.model;

public class AllBranch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.BRANCH_NO
     *
     * @mbggenerated
     */
    private Long branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.BRANCH_NAME
     *
     * @mbggenerated
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.UP_BRANCH_NO
     *
     * @mbggenerated
     */
    private Long upBranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.SYSNODE_ID
     *
     * @mbggenerated
     */
    private Long sysnodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.BRANCH_TYPE
     *
     * @mbggenerated
     */
    private String branchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.BRANCH_ZONE
     *
     * @mbggenerated
     */
    private Long branchZone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.COMPANY_NO
     *
     * @mbggenerated
     */
    private Long companyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.TREE_LEVEL
     *
     * @mbggenerated
     */
    private Long treeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LOCAL_NO
     *
     * @mbggenerated
     */
    private String localNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.CSRC_CODE
     *
     * @mbggenerated
     */
    private String csrcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.CONTACT
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.ZIPCODE
     *
     * @mbggenerated
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL1
     *
     * @mbggenerated
     */
    private Long level1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL2
     *
     * @mbggenerated
     */
    private Long level2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL3
     *
     * @mbggenerated
     */
    private Long level3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL4
     *
     * @mbggenerated
     */
    private Long level4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL5
     *
     * @mbggenerated
     */
    private Long level5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL6
     *
     * @mbggenerated
     */
    private Long level6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL7
     *
     * @mbggenerated
     */
    private Long level7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL8
     *
     * @mbggenerated
     */
    private Long level8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL9
     *
     * @mbggenerated
     */
    private Long level9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.LEVEL10
     *
     * @mbggenerated
     */
    private Long level10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.BRANCH_CTRLSTR
     *
     * @mbggenerated
     */
    private String branchCtrlstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.CMCC_ID
     *
     * @mbggenerated
     */
    private String cmccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.EXCH_ID
     *
     * @mbggenerated
     */
    private String exchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.ORGAN_SYSNODE_ID
     *
     * @mbggenerated
     */
    private Long organSysnodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.BRANCH_KIND
     *
     * @mbggenerated
     */
    private String branchKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.PROVINCE_CODE
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.ALLBRANCH.CITY_CODE
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.BRANCH_NO
     *
     * @return the value of HS_USER.ALLBRANCH.BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.BRANCH_NO
     *
     * @param branchNo the value for HS_USER.ALLBRANCH.BRANCH_NO
     *
     * @mbggenerated
     */
    public void setBranchNo(Long branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.BRANCH_NAME
     *
     * @return the value of HS_USER.ALLBRANCH.BRANCH_NAME
     *
     * @mbggenerated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.BRANCH_NAME
     *
     * @param branchName the value for HS_USER.ALLBRANCH.BRANCH_NAME
     *
     * @mbggenerated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.UP_BRANCH_NO
     *
     * @return the value of HS_USER.ALLBRANCH.UP_BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getUpBranchNo() {
        return upBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.UP_BRANCH_NO
     *
     * @param upBranchNo the value for HS_USER.ALLBRANCH.UP_BRANCH_NO
     *
     * @mbggenerated
     */
    public void setUpBranchNo(Long upBranchNo) {
        this.upBranchNo = upBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.SYSNODE_ID
     *
     * @return the value of HS_USER.ALLBRANCH.SYSNODE_ID
     *
     * @mbggenerated
     */
    public Long getSysnodeId() {
        return sysnodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.SYSNODE_ID
     *
     * @param sysnodeId the value for HS_USER.ALLBRANCH.SYSNODE_ID
     *
     * @mbggenerated
     */
    public void setSysnodeId(Long sysnodeId) {
        this.sysnodeId = sysnodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.BRANCH_TYPE
     *
     * @return the value of HS_USER.ALLBRANCH.BRANCH_TYPE
     *
     * @mbggenerated
     */
    public String getBranchType() {
        return branchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.BRANCH_TYPE
     *
     * @param branchType the value for HS_USER.ALLBRANCH.BRANCH_TYPE
     *
     * @mbggenerated
     */
    public void setBranchType(String branchType) {
        this.branchType = branchType == null ? null : branchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.BRANCH_ZONE
     *
     * @return the value of HS_USER.ALLBRANCH.BRANCH_ZONE
     *
     * @mbggenerated
     */
    public Long getBranchZone() {
        return branchZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.BRANCH_ZONE
     *
     * @param branchZone the value for HS_USER.ALLBRANCH.BRANCH_ZONE
     *
     * @mbggenerated
     */
    public void setBranchZone(Long branchZone) {
        this.branchZone = branchZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.COMPANY_NO
     *
     * @return the value of HS_USER.ALLBRANCH.COMPANY_NO
     *
     * @mbggenerated
     */
    public Long getCompanyNo() {
        return companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.COMPANY_NO
     *
     * @param companyNo the value for HS_USER.ALLBRANCH.COMPANY_NO
     *
     * @mbggenerated
     */
    public void setCompanyNo(Long companyNo) {
        this.companyNo = companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.TREE_LEVEL
     *
     * @return the value of HS_USER.ALLBRANCH.TREE_LEVEL
     *
     * @mbggenerated
     */
    public Long getTreeLevel() {
        return treeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.TREE_LEVEL
     *
     * @param treeLevel the value for HS_USER.ALLBRANCH.TREE_LEVEL
     *
     * @mbggenerated
     */
    public void setTreeLevel(Long treeLevel) {
        this.treeLevel = treeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LOCAL_NO
     *
     * @return the value of HS_USER.ALLBRANCH.LOCAL_NO
     *
     * @mbggenerated
     */
    public String getLocalNo() {
        return localNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LOCAL_NO
     *
     * @param localNo the value for HS_USER.ALLBRANCH.LOCAL_NO
     *
     * @mbggenerated
     */
    public void setLocalNo(String localNo) {
        this.localNo = localNo == null ? null : localNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.CSRC_CODE
     *
     * @return the value of HS_USER.ALLBRANCH.CSRC_CODE
     *
     * @mbggenerated
     */
    public String getCsrcCode() {
        return csrcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.CSRC_CODE
     *
     * @param csrcCode the value for HS_USER.ALLBRANCH.CSRC_CODE
     *
     * @mbggenerated
     */
    public void setCsrcCode(String csrcCode) {
        this.csrcCode = csrcCode == null ? null : csrcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.CONTACT
     *
     * @return the value of HS_USER.ALLBRANCH.CONTACT
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.CONTACT
     *
     * @param contact the value for HS_USER.ALLBRANCH.CONTACT
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.TELEPHONE
     *
     * @return the value of HS_USER.ALLBRANCH.TELEPHONE
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.TELEPHONE
     *
     * @param telephone the value for HS_USER.ALLBRANCH.TELEPHONE
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.ZIPCODE
     *
     * @return the value of HS_USER.ALLBRANCH.ZIPCODE
     *
     * @mbggenerated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.ZIPCODE
     *
     * @param zipcode the value for HS_USER.ALLBRANCH.ZIPCODE
     *
     * @mbggenerated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.ADDRESS
     *
     * @return the value of HS_USER.ALLBRANCH.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.ADDRESS
     *
     * @param address the value for HS_USER.ALLBRANCH.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL1
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL1
     *
     * @mbggenerated
     */
    public Long getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL1
     *
     * @param level1 the value for HS_USER.ALLBRANCH.LEVEL1
     *
     * @mbggenerated
     */
    public void setLevel1(Long level1) {
        this.level1 = level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL2
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL2
     *
     * @mbggenerated
     */
    public Long getLevel2() {
        return level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL2
     *
     * @param level2 the value for HS_USER.ALLBRANCH.LEVEL2
     *
     * @mbggenerated
     */
    public void setLevel2(Long level2) {
        this.level2 = level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL3
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL3
     *
     * @mbggenerated
     */
    public Long getLevel3() {
        return level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL3
     *
     * @param level3 the value for HS_USER.ALLBRANCH.LEVEL3
     *
     * @mbggenerated
     */
    public void setLevel3(Long level3) {
        this.level3 = level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL4
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL4
     *
     * @mbggenerated
     */
    public Long getLevel4() {
        return level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL4
     *
     * @param level4 the value for HS_USER.ALLBRANCH.LEVEL4
     *
     * @mbggenerated
     */
    public void setLevel4(Long level4) {
        this.level4 = level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL5
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL5
     *
     * @mbggenerated
     */
    public Long getLevel5() {
        return level5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL5
     *
     * @param level5 the value for HS_USER.ALLBRANCH.LEVEL5
     *
     * @mbggenerated
     */
    public void setLevel5(Long level5) {
        this.level5 = level5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL6
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL6
     *
     * @mbggenerated
     */
    public Long getLevel6() {
        return level6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL6
     *
     * @param level6 the value for HS_USER.ALLBRANCH.LEVEL6
     *
     * @mbggenerated
     */
    public void setLevel6(Long level6) {
        this.level6 = level6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL7
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL7
     *
     * @mbggenerated
     */
    public Long getLevel7() {
        return level7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL7
     *
     * @param level7 the value for HS_USER.ALLBRANCH.LEVEL7
     *
     * @mbggenerated
     */
    public void setLevel7(Long level7) {
        this.level7 = level7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL8
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL8
     *
     * @mbggenerated
     */
    public Long getLevel8() {
        return level8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL8
     *
     * @param level8 the value for HS_USER.ALLBRANCH.LEVEL8
     *
     * @mbggenerated
     */
    public void setLevel8(Long level8) {
        this.level8 = level8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL9
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL9
     *
     * @mbggenerated
     */
    public Long getLevel9() {
        return level9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL9
     *
     * @param level9 the value for HS_USER.ALLBRANCH.LEVEL9
     *
     * @mbggenerated
     */
    public void setLevel9(Long level9) {
        this.level9 = level9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.LEVEL10
     *
     * @return the value of HS_USER.ALLBRANCH.LEVEL10
     *
     * @mbggenerated
     */
    public Long getLevel10() {
        return level10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.LEVEL10
     *
     * @param level10 the value for HS_USER.ALLBRANCH.LEVEL10
     *
     * @mbggenerated
     */
    public void setLevel10(Long level10) {
        this.level10 = level10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.BRANCH_CTRLSTR
     *
     * @return the value of HS_USER.ALLBRANCH.BRANCH_CTRLSTR
     *
     * @mbggenerated
     */
    public String getBranchCtrlstr() {
        return branchCtrlstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.BRANCH_CTRLSTR
     *
     * @param branchCtrlstr the value for HS_USER.ALLBRANCH.BRANCH_CTRLSTR
     *
     * @mbggenerated
     */
    public void setBranchCtrlstr(String branchCtrlstr) {
        this.branchCtrlstr = branchCtrlstr == null ? null : branchCtrlstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.CMCC_ID
     *
     * @return the value of HS_USER.ALLBRANCH.CMCC_ID
     *
     * @mbggenerated
     */
    public String getCmccId() {
        return cmccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.CMCC_ID
     *
     * @param cmccId the value for HS_USER.ALLBRANCH.CMCC_ID
     *
     * @mbggenerated
     */
    public void setCmccId(String cmccId) {
        this.cmccId = cmccId == null ? null : cmccId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.EXCH_ID
     *
     * @return the value of HS_USER.ALLBRANCH.EXCH_ID
     *
     * @mbggenerated
     */
    public String getExchId() {
        return exchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.EXCH_ID
     *
     * @param exchId the value for HS_USER.ALLBRANCH.EXCH_ID
     *
     * @mbggenerated
     */
    public void setExchId(String exchId) {
        this.exchId = exchId == null ? null : exchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.E_MAIL
     *
     * @return the value of HS_USER.ALLBRANCH.E_MAIL
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.E_MAIL
     *
     * @param eMail the value for HS_USER.ALLBRANCH.E_MAIL
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.ORGAN_SYSNODE_ID
     *
     * @return the value of HS_USER.ALLBRANCH.ORGAN_SYSNODE_ID
     *
     * @mbggenerated
     */
    public Long getOrganSysnodeId() {
        return organSysnodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.ORGAN_SYSNODE_ID
     *
     * @param organSysnodeId the value for HS_USER.ALLBRANCH.ORGAN_SYSNODE_ID
     *
     * @mbggenerated
     */
    public void setOrganSysnodeId(Long organSysnodeId) {
        this.organSysnodeId = organSysnodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.BRANCH_KIND
     *
     * @return the value of HS_USER.ALLBRANCH.BRANCH_KIND
     *
     * @mbggenerated
     */
    public String getBranchKind() {
        return branchKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.BRANCH_KIND
     *
     * @param branchKind the value for HS_USER.ALLBRANCH.BRANCH_KIND
     *
     * @mbggenerated
     */
    public void setBranchKind(String branchKind) {
        this.branchKind = branchKind == null ? null : branchKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.PROVINCE_CODE
     *
     * @return the value of HS_USER.ALLBRANCH.PROVINCE_CODE
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.PROVINCE_CODE
     *
     * @param provinceCode the value for HS_USER.ALLBRANCH.PROVINCE_CODE
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.ALLBRANCH.CITY_CODE
     *
     * @return the value of HS_USER.ALLBRANCH.CITY_CODE
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.ALLBRANCH.CITY_CODE
     *
     * @param cityCode the value for HS_USER.ALLBRANCH.CITY_CODE
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }
}