package com.paul.base.sync.oracle.user.model;

import java.math.BigDecimal;

public class Bfare2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.FARE_KIND
     *
     * @mbggenerated
     */
    private Long fareKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.FARE_TYPE
     *
     * @mbggenerated
     */
    private String fareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    private String exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.STOCK_TYPE
     *
     * @mbggenerated
     */
    private String stockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.ENTRUST_BS
     *
     * @mbggenerated
     */
    private String entrustBs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.ENTRUST_WAY
     *
     * @mbggenerated
     */
    private String entrustWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.MONEY_TYPE
     *
     * @mbggenerated
     */
    private String moneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.ENTRUST_TYPE
     *
     * @mbggenerated
     */
    private String entrustType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.BRANCH_NO
     *
     * @mbggenerated
     */
    private Long branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.BALANCE_RATIO
     *
     * @mbggenerated
     */
    private BigDecimal balanceRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.PAR_RATIO
     *
     * @mbggenerated
     */
    private BigDecimal parRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.MIN_FARE
     *
     * @mbggenerated
     */
    private BigDecimal minFare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.MAX_FARE
     *
     * @mbggenerated
     */
    private BigDecimal maxFare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.DISPART_COUNT
     *
     * @mbggenerated
     */
    private String dispartCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.REBATE_FLAG
     *
     * @mbggenerated
     */
    private String rebateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.REBATE_RATIO
     *
     * @mbggenerated
     */
    private BigDecimal rebateRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.MIN_RATIO
     *
     * @mbggenerated
     */
    private BigDecimal minRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.SEGMENT_FLAG
     *
     * @mbggenerated
     */
    private String segmentFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.BFARE2.SEGMENT_KIND
     *
     * @mbggenerated
     */
    private Long segmentKind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.FARE_KIND
     *
     * @return the value of HS_USER.BFARE2.FARE_KIND
     *
     * @mbggenerated
     */
    public Long getFareKind() {
        return fareKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.FARE_KIND
     *
     * @param fareKind the value for HS_USER.BFARE2.FARE_KIND
     *
     * @mbggenerated
     */
    public void setFareKind(Long fareKind) {
        this.fareKind = fareKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.FARE_TYPE
     *
     * @return the value of HS_USER.BFARE2.FARE_TYPE
     *
     * @mbggenerated
     */
    public String getFareType() {
        return fareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.FARE_TYPE
     *
     * @param fareType the value for HS_USER.BFARE2.FARE_TYPE
     *
     * @mbggenerated
     */
    public void setFareType(String fareType) {
        this.fareType = fareType == null ? null : fareType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.EXCHANGE_TYPE
     *
     * @return the value of HS_USER.BFARE2.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public String getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.EXCHANGE_TYPE
     *
     * @param exchangeType the value for HS_USER.BFARE2.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType == null ? null : exchangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.STOCK_TYPE
     *
     * @return the value of HS_USER.BFARE2.STOCK_TYPE
     *
     * @mbggenerated
     */
    public String getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.STOCK_TYPE
     *
     * @param stockType the value for HS_USER.BFARE2.STOCK_TYPE
     *
     * @mbggenerated
     */
    public void setStockType(String stockType) {
        this.stockType = stockType == null ? null : stockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.ENTRUST_BS
     *
     * @return the value of HS_USER.BFARE2.ENTRUST_BS
     *
     * @mbggenerated
     */
    public String getEntrustBs() {
        return entrustBs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.ENTRUST_BS
     *
     * @param entrustBs the value for HS_USER.BFARE2.ENTRUST_BS
     *
     * @mbggenerated
     */
    public void setEntrustBs(String entrustBs) {
        this.entrustBs = entrustBs == null ? null : entrustBs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.ENTRUST_WAY
     *
     * @return the value of HS_USER.BFARE2.ENTRUST_WAY
     *
     * @mbggenerated
     */
    public String getEntrustWay() {
        return entrustWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.ENTRUST_WAY
     *
     * @param entrustWay the value for HS_USER.BFARE2.ENTRUST_WAY
     *
     * @mbggenerated
     */
    public void setEntrustWay(String entrustWay) {
        this.entrustWay = entrustWay == null ? null : entrustWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.MONEY_TYPE
     *
     * @return the value of HS_USER.BFARE2.MONEY_TYPE
     *
     * @mbggenerated
     */
    public String getMoneyType() {
        return moneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.MONEY_TYPE
     *
     * @param moneyType the value for HS_USER.BFARE2.MONEY_TYPE
     *
     * @mbggenerated
     */
    public void setMoneyType(String moneyType) {
        this.moneyType = moneyType == null ? null : moneyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.ENTRUST_TYPE
     *
     * @return the value of HS_USER.BFARE2.ENTRUST_TYPE
     *
     * @mbggenerated
     */
    public String getEntrustType() {
        return entrustType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.ENTRUST_TYPE
     *
     * @param entrustType the value for HS_USER.BFARE2.ENTRUST_TYPE
     *
     * @mbggenerated
     */
    public void setEntrustType(String entrustType) {
        this.entrustType = entrustType == null ? null : entrustType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.BRANCH_NO
     *
     * @return the value of HS_USER.BFARE2.BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.BRANCH_NO
     *
     * @param branchNo the value for HS_USER.BFARE2.BRANCH_NO
     *
     * @mbggenerated
     */
    public void setBranchNo(Long branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.BALANCE_RATIO
     *
     * @return the value of HS_USER.BFARE2.BALANCE_RATIO
     *
     * @mbggenerated
     */
    public BigDecimal getBalanceRatio() {
        return balanceRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.BALANCE_RATIO
     *
     * @param balanceRatio the value for HS_USER.BFARE2.BALANCE_RATIO
     *
     * @mbggenerated
     */
    public void setBalanceRatio(BigDecimal balanceRatio) {
        this.balanceRatio = balanceRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.PAR_RATIO
     *
     * @return the value of HS_USER.BFARE2.PAR_RATIO
     *
     * @mbggenerated
     */
    public BigDecimal getParRatio() {
        return parRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.PAR_RATIO
     *
     * @param parRatio the value for HS_USER.BFARE2.PAR_RATIO
     *
     * @mbggenerated
     */
    public void setParRatio(BigDecimal parRatio) {
        this.parRatio = parRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.MIN_FARE
     *
     * @return the value of HS_USER.BFARE2.MIN_FARE
     *
     * @mbggenerated
     */
    public BigDecimal getMinFare() {
        return minFare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.MIN_FARE
     *
     * @param minFare the value for HS_USER.BFARE2.MIN_FARE
     *
     * @mbggenerated
     */
    public void setMinFare(BigDecimal minFare) {
        this.minFare = minFare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.MAX_FARE
     *
     * @return the value of HS_USER.BFARE2.MAX_FARE
     *
     * @mbggenerated
     */
    public BigDecimal getMaxFare() {
        return maxFare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.MAX_FARE
     *
     * @param maxFare the value for HS_USER.BFARE2.MAX_FARE
     *
     * @mbggenerated
     */
    public void setMaxFare(BigDecimal maxFare) {
        this.maxFare = maxFare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.DISPART_COUNT
     *
     * @return the value of HS_USER.BFARE2.DISPART_COUNT
     *
     * @mbggenerated
     */
    public String getDispartCount() {
        return dispartCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.DISPART_COUNT
     *
     * @param dispartCount the value for HS_USER.BFARE2.DISPART_COUNT
     *
     * @mbggenerated
     */
    public void setDispartCount(String dispartCount) {
        this.dispartCount = dispartCount == null ? null : dispartCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.REBATE_FLAG
     *
     * @return the value of HS_USER.BFARE2.REBATE_FLAG
     *
     * @mbggenerated
     */
    public String getRebateFlag() {
        return rebateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.REBATE_FLAG
     *
     * @param rebateFlag the value for HS_USER.BFARE2.REBATE_FLAG
     *
     * @mbggenerated
     */
    public void setRebateFlag(String rebateFlag) {
        this.rebateFlag = rebateFlag == null ? null : rebateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.REBATE_RATIO
     *
     * @return the value of HS_USER.BFARE2.REBATE_RATIO
     *
     * @mbggenerated
     */
    public BigDecimal getRebateRatio() {
        return rebateRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.REBATE_RATIO
     *
     * @param rebateRatio the value for HS_USER.BFARE2.REBATE_RATIO
     *
     * @mbggenerated
     */
    public void setRebateRatio(BigDecimal rebateRatio) {
        this.rebateRatio = rebateRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.MIN_RATIO
     *
     * @return the value of HS_USER.BFARE2.MIN_RATIO
     *
     * @mbggenerated
     */
    public BigDecimal getMinRatio() {
        return minRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.MIN_RATIO
     *
     * @param minRatio the value for HS_USER.BFARE2.MIN_RATIO
     *
     * @mbggenerated
     */
    public void setMinRatio(BigDecimal minRatio) {
        this.minRatio = minRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.SEGMENT_FLAG
     *
     * @return the value of HS_USER.BFARE2.SEGMENT_FLAG
     *
     * @mbggenerated
     */
    public String getSegmentFlag() {
        return segmentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.SEGMENT_FLAG
     *
     * @param segmentFlag the value for HS_USER.BFARE2.SEGMENT_FLAG
     *
     * @mbggenerated
     */
    public void setSegmentFlag(String segmentFlag) {
        this.segmentFlag = segmentFlag == null ? null : segmentFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.BFARE2.SEGMENT_KIND
     *
     * @return the value of HS_USER.BFARE2.SEGMENT_KIND
     *
     * @mbggenerated
     */
    public Long getSegmentKind() {
        return segmentKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.BFARE2.SEGMENT_KIND
     *
     * @param segmentKind the value for HS_USER.BFARE2.SEGMENT_KIND
     *
     * @mbggenerated
     */
    public void setSegmentKind(Long segmentKind) {
        this.segmentKind = segmentKind;
    }
}