package com.paul.base.sync.oracle.user.model;

public class Seats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    private String exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.SEAT_NO
     *
     * @mbggenerated
     */
    private String seatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.FIRM_ID
     *
     * @mbggenerated
     */
    private String firmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.BRANCH_NO
     *
     * @mbggenerated
     */
    private Long branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.SEAT_PROP
     *
     * @mbggenerated
     */
    private String seatProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.SEATVIP_FLAG
     *
     * @mbggenerated
     */
    private String seatvipFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.EN_STOCK_TYPE
     *
     * @mbggenerated
     */
    private String enStockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.EN_CLIENT_GROUP
     *
     * @mbggenerated
     */
    private String enClientGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.DEFAULT_MARK
     *
     * @mbggenerated
     */
    private String defaultMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.CASHREPORT_FLAG
     *
     * @mbggenerated
     */
    private String cashreportFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.SEATORGAN_FLAG
     *
     * @mbggenerated
     */
    private String seatorganFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.SEATS.ICS_ETFVOUCHER_FLAG
     *
     * @mbggenerated
     */
    private String icsEtfvoucherFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.EXCHANGE_TYPE
     *
     * @return the value of HS_USER.SEATS.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public String getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.EXCHANGE_TYPE
     *
     * @param exchangeType the value for HS_USER.SEATS.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType == null ? null : exchangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.SEAT_NO
     *
     * @return the value of HS_USER.SEATS.SEAT_NO
     *
     * @mbggenerated
     */
    public String getSeatNo() {
        return seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.SEAT_NO
     *
     * @param seatNo the value for HS_USER.SEATS.SEAT_NO
     *
     * @mbggenerated
     */
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo == null ? null : seatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.FIRM_ID
     *
     * @return the value of HS_USER.SEATS.FIRM_ID
     *
     * @mbggenerated
     */
    public String getFirmId() {
        return firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.FIRM_ID
     *
     * @param firmId the value for HS_USER.SEATS.FIRM_ID
     *
     * @mbggenerated
     */
    public void setFirmId(String firmId) {
        this.firmId = firmId == null ? null : firmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.BRANCH_NO
     *
     * @return the value of HS_USER.SEATS.BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.BRANCH_NO
     *
     * @param branchNo the value for HS_USER.SEATS.BRANCH_NO
     *
     * @mbggenerated
     */
    public void setBranchNo(Long branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.SEAT_PROP
     *
     * @return the value of HS_USER.SEATS.SEAT_PROP
     *
     * @mbggenerated
     */
    public String getSeatProp() {
        return seatProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.SEAT_PROP
     *
     * @param seatProp the value for HS_USER.SEATS.SEAT_PROP
     *
     * @mbggenerated
     */
    public void setSeatProp(String seatProp) {
        this.seatProp = seatProp == null ? null : seatProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.SEATVIP_FLAG
     *
     * @return the value of HS_USER.SEATS.SEATVIP_FLAG
     *
     * @mbggenerated
     */
    public String getSeatvipFlag() {
        return seatvipFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.SEATVIP_FLAG
     *
     * @param seatvipFlag the value for HS_USER.SEATS.SEATVIP_FLAG
     *
     * @mbggenerated
     */
    public void setSeatvipFlag(String seatvipFlag) {
        this.seatvipFlag = seatvipFlag == null ? null : seatvipFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.EN_STOCK_TYPE
     *
     * @return the value of HS_USER.SEATS.EN_STOCK_TYPE
     *
     * @mbggenerated
     */
    public String getEnStockType() {
        return enStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.EN_STOCK_TYPE
     *
     * @param enStockType the value for HS_USER.SEATS.EN_STOCK_TYPE
     *
     * @mbggenerated
     */
    public void setEnStockType(String enStockType) {
        this.enStockType = enStockType == null ? null : enStockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.EN_CLIENT_GROUP
     *
     * @return the value of HS_USER.SEATS.EN_CLIENT_GROUP
     *
     * @mbggenerated
     */
    public String getEnClientGroup() {
        return enClientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.EN_CLIENT_GROUP
     *
     * @param enClientGroup the value for HS_USER.SEATS.EN_CLIENT_GROUP
     *
     * @mbggenerated
     */
    public void setEnClientGroup(String enClientGroup) {
        this.enClientGroup = enClientGroup == null ? null : enClientGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.DEFAULT_MARK
     *
     * @return the value of HS_USER.SEATS.DEFAULT_MARK
     *
     * @mbggenerated
     */
    public String getDefaultMark() {
        return defaultMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.DEFAULT_MARK
     *
     * @param defaultMark the value for HS_USER.SEATS.DEFAULT_MARK
     *
     * @mbggenerated
     */
    public void setDefaultMark(String defaultMark) {
        this.defaultMark = defaultMark == null ? null : defaultMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.REMARK
     *
     * @return the value of HS_USER.SEATS.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.REMARK
     *
     * @param remark the value for HS_USER.SEATS.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.CASHREPORT_FLAG
     *
     * @return the value of HS_USER.SEATS.CASHREPORT_FLAG
     *
     * @mbggenerated
     */
    public String getCashreportFlag() {
        return cashreportFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.CASHREPORT_FLAG
     *
     * @param cashreportFlag the value for HS_USER.SEATS.CASHREPORT_FLAG
     *
     * @mbggenerated
     */
    public void setCashreportFlag(String cashreportFlag) {
        this.cashreportFlag = cashreportFlag == null ? null : cashreportFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.SEATORGAN_FLAG
     *
     * @return the value of HS_USER.SEATS.SEATORGAN_FLAG
     *
     * @mbggenerated
     */
    public String getSeatorganFlag() {
        return seatorganFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.SEATORGAN_FLAG
     *
     * @param seatorganFlag the value for HS_USER.SEATS.SEATORGAN_FLAG
     *
     * @mbggenerated
     */
    public void setSeatorganFlag(String seatorganFlag) {
        this.seatorganFlag = seatorganFlag == null ? null : seatorganFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.SEATS.ICS_ETFVOUCHER_FLAG
     *
     * @return the value of HS_USER.SEATS.ICS_ETFVOUCHER_FLAG
     *
     * @mbggenerated
     */
    public String getIcsEtfvoucherFlag() {
        return icsEtfvoucherFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.SEATS.ICS_ETFVOUCHER_FLAG
     *
     * @param icsEtfvoucherFlag the value for HS_USER.SEATS.ICS_ETFVOUCHER_FLAG
     *
     * @mbggenerated
     */
    public void setIcsEtfvoucherFlag(String icsEtfvoucherFlag) {
        this.icsEtfvoucherFlag = icsEtfvoucherFlag == null ? null : icsEtfvoucherFlag.trim();
    }
}