package com.paul.base.sync.oracle.user.model;

import java.math.BigDecimal;

public class StkCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    private String exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STOCK_CODE
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STOCK_TYPE
     *
     * @mbggenerated
     */
    private String stockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.INTERNAL_CODE
     *
     * @mbggenerated
     */
    private String internalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.FROZEN_CODE
     *
     * @mbggenerated
     */
    private String frozenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MONEY_TYPE
     *
     * @mbggenerated
     */
    private String moneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STOCK_NAME
     *
     * @mbggenerated
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.SPELL_CODE
     *
     * @mbggenerated
     */
    private String spellCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.RELATIVE_CODE
     *
     * @mbggenerated
     */
    private String relativeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STKCODE_STATUS
     *
     * @mbggenerated
     */
    private String stkcodeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BOND_TERM
     *
     * @mbggenerated
     */
    private Long bondTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.DEFAULT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal defaultPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BASE_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal basePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.LAST_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal lastPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.CLOSE_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.NET_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal netValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.UP_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal upPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.DOWN_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal downPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.HIGH_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal highAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.LOW_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal lowAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.TRUSTEE
     *
     * @mbggenerated
     */
    private String trustee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.OVERDRAW
     *
     * @mbggenerated
     */
    private String overdraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.ASSET_FLAG
     *
     * @mbggenerated
     */
    private String assetFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.AMOUNT_PER_HAND
     *
     * @mbggenerated
     */
    private Long amountPerHand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STORE_UNIT
     *
     * @mbggenerated
     */
    private Long storeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.REPORT_UNIT
     *
     * @mbggenerated
     */
    private Long reportUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BUY_UNIT
     *
     * @mbggenerated
     */
    private Long buyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.SELL_UNIT
     *
     * @mbggenerated
     */
    private Long sellUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.PRICE_STEP
     *
     * @mbggenerated
     */
    private Long priceStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.PRICE_GRADE
     *
     * @mbggenerated
     */
    private Long priceGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.REPORT_DIRECTION
     *
     * @mbggenerated
     */
    private String reportDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.FUND_DIRECTION
     *
     * @mbggenerated
     */
    private String fundDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STOCK_DIRECTION
     *
     * @mbggenerated
     */
    private String stockDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.FUND_FROZEN
     *
     * @mbggenerated
     */
    private String fundFrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.FUND_REAL_BACK
     *
     * @mbggenerated
     */
    private String fundRealBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STOCK_REAL_BACK
     *
     * @mbggenerated
     */
    private String stockRealBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MATCH_TYPE
     *
     * @mbggenerated
     */
    private String matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.TN_TYPE
     *
     * @mbggenerated
     */
    private String tnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.FUND_BACK_N
     *
     * @mbggenerated
     */
    private Short fundBackN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STOCK_BACK_N
     *
     * @mbggenerated
     */
    private Short stockBackN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.PAR_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal parValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.HOLD_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal holdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MARKET_DATE
     *
     * @mbggenerated
     */
    private Long marketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.DEFAULTPRICE_TYPE
     *
     * @mbggenerated
     */
    private String defaultpriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.LIMITPRICE_TYPE
     *
     * @mbggenerated
     */
    private String limitpriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BASEPRICE_TYPE
     *
     * @mbggenerated
     */
    private String basepriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.LIMIT_VALUE_UP
     *
     * @mbggenerated
     */
    private Long limitValueUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.LIMIT_VALUE_LOW
     *
     * @mbggenerated
     */
    private Long limitValueLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BUY_CLIENT
     *
     * @mbggenerated
     */
    private String buyClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.SELL_CLIENT
     *
     * @mbggenerated
     */
    private String sellClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BUY_HOLDER
     *
     * @mbggenerated
     */
    private String buyHolder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.SELL_HOLDER
     *
     * @mbggenerated
     */
    private String sellHolder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.EN_ENTRUST_WAY
     *
     * @mbggenerated
     */
    private String enEntrustWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.ELIG_RISK_LEVEL
     *
     * @mbggenerated
     */
    private Long eligRiskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.LOW_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal lowBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.HIGH_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal highBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.CANCEL_LOW_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal cancelLowBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.CANCEL_HIGH_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal cancelHighBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.ISSUE_DATE
     *
     * @mbggenerated
     */
    private Long issueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Long modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.BONDINV_FLAG
     *
     * @mbggenerated
     */
    private String bondinvFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.DELIST_FLAG
     *
     * @mbggenerated
     */
    private String delistFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.DELIST_DATE
     *
     * @mbggenerated
     */
    private Long delistDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STBTRANS_TYPE
     *
     * @mbggenerated
     */
    private String stbtransType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.SUB_STOCK_TYPE
     *
     * @mbggenerated
     */
    private String subStockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STBTRANS_STATUS
     *
     * @mbggenerated
     */
    private String stbtransStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.STKCODE_CTRLSTR
     *
     * @mbggenerated
     */
    private String stkcodeCtrlstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.EXDIVIDEND_FLAG
     *
     * @mbggenerated
     */
    private String exdividendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MARKETMAKER_AMOUNT
     *
     * @mbggenerated
     */
    private Long marketmakerAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.TRANS_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal transPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MARKET_HIGH_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal marketHighAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_USER.STKCODE.MARKET_LOW_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal marketLowAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.EXCHANGE_TYPE
     *
     * @return the value of HS_USER.STKCODE.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public String getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.EXCHANGE_TYPE
     *
     * @param exchangeType the value for HS_USER.STKCODE.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType == null ? null : exchangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STOCK_CODE
     *
     * @return the value of HS_USER.STKCODE.STOCK_CODE
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STOCK_CODE
     *
     * @param stockCode the value for HS_USER.STKCODE.STOCK_CODE
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STOCK_TYPE
     *
     * @return the value of HS_USER.STKCODE.STOCK_TYPE
     *
     * @mbggenerated
     */
    public String getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STOCK_TYPE
     *
     * @param stockType the value for HS_USER.STKCODE.STOCK_TYPE
     *
     * @mbggenerated
     */
    public void setStockType(String stockType) {
        this.stockType = stockType == null ? null : stockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.INTERNAL_CODE
     *
     * @return the value of HS_USER.STKCODE.INTERNAL_CODE
     *
     * @mbggenerated
     */
    public String getInternalCode() {
        return internalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.INTERNAL_CODE
     *
     * @param internalCode the value for HS_USER.STKCODE.INTERNAL_CODE
     *
     * @mbggenerated
     */
    public void setInternalCode(String internalCode) {
        this.internalCode = internalCode == null ? null : internalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.FROZEN_CODE
     *
     * @return the value of HS_USER.STKCODE.FROZEN_CODE
     *
     * @mbggenerated
     */
    public String getFrozenCode() {
        return frozenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.FROZEN_CODE
     *
     * @param frozenCode the value for HS_USER.STKCODE.FROZEN_CODE
     *
     * @mbggenerated
     */
    public void setFrozenCode(String frozenCode) {
        this.frozenCode = frozenCode == null ? null : frozenCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MONEY_TYPE
     *
     * @return the value of HS_USER.STKCODE.MONEY_TYPE
     *
     * @mbggenerated
     */
    public String getMoneyType() {
        return moneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MONEY_TYPE
     *
     * @param moneyType the value for HS_USER.STKCODE.MONEY_TYPE
     *
     * @mbggenerated
     */
    public void setMoneyType(String moneyType) {
        this.moneyType = moneyType == null ? null : moneyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STOCK_NAME
     *
     * @return the value of HS_USER.STKCODE.STOCK_NAME
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STOCK_NAME
     *
     * @param stockName the value for HS_USER.STKCODE.STOCK_NAME
     *
     * @mbggenerated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.SPELL_CODE
     *
     * @return the value of HS_USER.STKCODE.SPELL_CODE
     *
     * @mbggenerated
     */
    public String getSpellCode() {
        return spellCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.SPELL_CODE
     *
     * @param spellCode the value for HS_USER.STKCODE.SPELL_CODE
     *
     * @mbggenerated
     */
    public void setSpellCode(String spellCode) {
        this.spellCode = spellCode == null ? null : spellCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.RELATIVE_CODE
     *
     * @return the value of HS_USER.STKCODE.RELATIVE_CODE
     *
     * @mbggenerated
     */
    public String getRelativeCode() {
        return relativeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.RELATIVE_CODE
     *
     * @param relativeCode the value for HS_USER.STKCODE.RELATIVE_CODE
     *
     * @mbggenerated
     */
    public void setRelativeCode(String relativeCode) {
        this.relativeCode = relativeCode == null ? null : relativeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STKCODE_STATUS
     *
     * @return the value of HS_USER.STKCODE.STKCODE_STATUS
     *
     * @mbggenerated
     */
    public String getStkcodeStatus() {
        return stkcodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STKCODE_STATUS
     *
     * @param stkcodeStatus the value for HS_USER.STKCODE.STKCODE_STATUS
     *
     * @mbggenerated
     */
    public void setStkcodeStatus(String stkcodeStatus) {
        this.stkcodeStatus = stkcodeStatus == null ? null : stkcodeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BOND_TERM
     *
     * @return the value of HS_USER.STKCODE.BOND_TERM
     *
     * @mbggenerated
     */
    public Long getBondTerm() {
        return bondTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BOND_TERM
     *
     * @param bondTerm the value for HS_USER.STKCODE.BOND_TERM
     *
     * @mbggenerated
     */
    public void setBondTerm(Long bondTerm) {
        this.bondTerm = bondTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.DEFAULT_PRICE
     *
     * @return the value of HS_USER.STKCODE.DEFAULT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getDefaultPrice() {
        return defaultPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.DEFAULT_PRICE
     *
     * @param defaultPrice the value for HS_USER.STKCODE.DEFAULT_PRICE
     *
     * @mbggenerated
     */
    public void setDefaultPrice(BigDecimal defaultPrice) {
        this.defaultPrice = defaultPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BASE_PRICE
     *
     * @return the value of HS_USER.STKCODE.BASE_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BASE_PRICE
     *
     * @param basePrice the value for HS_USER.STKCODE.BASE_PRICE
     *
     * @mbggenerated
     */
    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.LAST_PRICE
     *
     * @return the value of HS_USER.STKCODE.LAST_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getLastPrice() {
        return lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.LAST_PRICE
     *
     * @param lastPrice the value for HS_USER.STKCODE.LAST_PRICE
     *
     * @mbggenerated
     */
    public void setLastPrice(BigDecimal lastPrice) {
        this.lastPrice = lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.CLOSE_PRICE
     *
     * @return the value of HS_USER.STKCODE.CLOSE_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.CLOSE_PRICE
     *
     * @param closePrice the value for HS_USER.STKCODE.CLOSE_PRICE
     *
     * @mbggenerated
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.NET_VALUE
     *
     * @return the value of HS_USER.STKCODE.NET_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getNetValue() {
        return netValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.NET_VALUE
     *
     * @param netValue the value for HS_USER.STKCODE.NET_VALUE
     *
     * @mbggenerated
     */
    public void setNetValue(BigDecimal netValue) {
        this.netValue = netValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.UP_PRICE
     *
     * @return the value of HS_USER.STKCODE.UP_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getUpPrice() {
        return upPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.UP_PRICE
     *
     * @param upPrice the value for HS_USER.STKCODE.UP_PRICE
     *
     * @mbggenerated
     */
    public void setUpPrice(BigDecimal upPrice) {
        this.upPrice = upPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.DOWN_PRICE
     *
     * @return the value of HS_USER.STKCODE.DOWN_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getDownPrice() {
        return downPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.DOWN_PRICE
     *
     * @param downPrice the value for HS_USER.STKCODE.DOWN_PRICE
     *
     * @mbggenerated
     */
    public void setDownPrice(BigDecimal downPrice) {
        this.downPrice = downPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.HIGH_AMOUNT
     *
     * @return the value of HS_USER.STKCODE.HIGH_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getHighAmount() {
        return highAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.HIGH_AMOUNT
     *
     * @param highAmount the value for HS_USER.STKCODE.HIGH_AMOUNT
     *
     * @mbggenerated
     */
    public void setHighAmount(BigDecimal highAmount) {
        this.highAmount = highAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.LOW_AMOUNT
     *
     * @return the value of HS_USER.STKCODE.LOW_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getLowAmount() {
        return lowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.LOW_AMOUNT
     *
     * @param lowAmount the value for HS_USER.STKCODE.LOW_AMOUNT
     *
     * @mbggenerated
     */
    public void setLowAmount(BigDecimal lowAmount) {
        this.lowAmount = lowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.TRUSTEE
     *
     * @return the value of HS_USER.STKCODE.TRUSTEE
     *
     * @mbggenerated
     */
    public String getTrustee() {
        return trustee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.TRUSTEE
     *
     * @param trustee the value for HS_USER.STKCODE.TRUSTEE
     *
     * @mbggenerated
     */
    public void setTrustee(String trustee) {
        this.trustee = trustee == null ? null : trustee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.OVERDRAW
     *
     * @return the value of HS_USER.STKCODE.OVERDRAW
     *
     * @mbggenerated
     */
    public String getOverdraw() {
        return overdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.OVERDRAW
     *
     * @param overdraw the value for HS_USER.STKCODE.OVERDRAW
     *
     * @mbggenerated
     */
    public void setOverdraw(String overdraw) {
        this.overdraw = overdraw == null ? null : overdraw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.ASSET_FLAG
     *
     * @return the value of HS_USER.STKCODE.ASSET_FLAG
     *
     * @mbggenerated
     */
    public String getAssetFlag() {
        return assetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.ASSET_FLAG
     *
     * @param assetFlag the value for HS_USER.STKCODE.ASSET_FLAG
     *
     * @mbggenerated
     */
    public void setAssetFlag(String assetFlag) {
        this.assetFlag = assetFlag == null ? null : assetFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.AMOUNT_PER_HAND
     *
     * @return the value of HS_USER.STKCODE.AMOUNT_PER_HAND
     *
     * @mbggenerated
     */
    public Long getAmountPerHand() {
        return amountPerHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.AMOUNT_PER_HAND
     *
     * @param amountPerHand the value for HS_USER.STKCODE.AMOUNT_PER_HAND
     *
     * @mbggenerated
     */
    public void setAmountPerHand(Long amountPerHand) {
        this.amountPerHand = amountPerHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STORE_UNIT
     *
     * @return the value of HS_USER.STKCODE.STORE_UNIT
     *
     * @mbggenerated
     */
    public Long getStoreUnit() {
        return storeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STORE_UNIT
     *
     * @param storeUnit the value for HS_USER.STKCODE.STORE_UNIT
     *
     * @mbggenerated
     */
    public void setStoreUnit(Long storeUnit) {
        this.storeUnit = storeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.REPORT_UNIT
     *
     * @return the value of HS_USER.STKCODE.REPORT_UNIT
     *
     * @mbggenerated
     */
    public Long getReportUnit() {
        return reportUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.REPORT_UNIT
     *
     * @param reportUnit the value for HS_USER.STKCODE.REPORT_UNIT
     *
     * @mbggenerated
     */
    public void setReportUnit(Long reportUnit) {
        this.reportUnit = reportUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BUY_UNIT
     *
     * @return the value of HS_USER.STKCODE.BUY_UNIT
     *
     * @mbggenerated
     */
    public Long getBuyUnit() {
        return buyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BUY_UNIT
     *
     * @param buyUnit the value for HS_USER.STKCODE.BUY_UNIT
     *
     * @mbggenerated
     */
    public void setBuyUnit(Long buyUnit) {
        this.buyUnit = buyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.SELL_UNIT
     *
     * @return the value of HS_USER.STKCODE.SELL_UNIT
     *
     * @mbggenerated
     */
    public Long getSellUnit() {
        return sellUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.SELL_UNIT
     *
     * @param sellUnit the value for HS_USER.STKCODE.SELL_UNIT
     *
     * @mbggenerated
     */
    public void setSellUnit(Long sellUnit) {
        this.sellUnit = sellUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.PRICE_STEP
     *
     * @return the value of HS_USER.STKCODE.PRICE_STEP
     *
     * @mbggenerated
     */
    public Long getPriceStep() {
        return priceStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.PRICE_STEP
     *
     * @param priceStep the value for HS_USER.STKCODE.PRICE_STEP
     *
     * @mbggenerated
     */
    public void setPriceStep(Long priceStep) {
        this.priceStep = priceStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.PRICE_GRADE
     *
     * @return the value of HS_USER.STKCODE.PRICE_GRADE
     *
     * @mbggenerated
     */
    public Long getPriceGrade() {
        return priceGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.PRICE_GRADE
     *
     * @param priceGrade the value for HS_USER.STKCODE.PRICE_GRADE
     *
     * @mbggenerated
     */
    public void setPriceGrade(Long priceGrade) {
        this.priceGrade = priceGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.REPORT_DIRECTION
     *
     * @return the value of HS_USER.STKCODE.REPORT_DIRECTION
     *
     * @mbggenerated
     */
    public String getReportDirection() {
        return reportDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.REPORT_DIRECTION
     *
     * @param reportDirection the value for HS_USER.STKCODE.REPORT_DIRECTION
     *
     * @mbggenerated
     */
    public void setReportDirection(String reportDirection) {
        this.reportDirection = reportDirection == null ? null : reportDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.FUND_DIRECTION
     *
     * @return the value of HS_USER.STKCODE.FUND_DIRECTION
     *
     * @mbggenerated
     */
    public String getFundDirection() {
        return fundDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.FUND_DIRECTION
     *
     * @param fundDirection the value for HS_USER.STKCODE.FUND_DIRECTION
     *
     * @mbggenerated
     */
    public void setFundDirection(String fundDirection) {
        this.fundDirection = fundDirection == null ? null : fundDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STOCK_DIRECTION
     *
     * @return the value of HS_USER.STKCODE.STOCK_DIRECTION
     *
     * @mbggenerated
     */
    public String getStockDirection() {
        return stockDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STOCK_DIRECTION
     *
     * @param stockDirection the value for HS_USER.STKCODE.STOCK_DIRECTION
     *
     * @mbggenerated
     */
    public void setStockDirection(String stockDirection) {
        this.stockDirection = stockDirection == null ? null : stockDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.FUND_FROZEN
     *
     * @return the value of HS_USER.STKCODE.FUND_FROZEN
     *
     * @mbggenerated
     */
    public String getFundFrozen() {
        return fundFrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.FUND_FROZEN
     *
     * @param fundFrozen the value for HS_USER.STKCODE.FUND_FROZEN
     *
     * @mbggenerated
     */
    public void setFundFrozen(String fundFrozen) {
        this.fundFrozen = fundFrozen == null ? null : fundFrozen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.FUND_REAL_BACK
     *
     * @return the value of HS_USER.STKCODE.FUND_REAL_BACK
     *
     * @mbggenerated
     */
    public String getFundRealBack() {
        return fundRealBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.FUND_REAL_BACK
     *
     * @param fundRealBack the value for HS_USER.STKCODE.FUND_REAL_BACK
     *
     * @mbggenerated
     */
    public void setFundRealBack(String fundRealBack) {
        this.fundRealBack = fundRealBack == null ? null : fundRealBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STOCK_REAL_BACK
     *
     * @return the value of HS_USER.STKCODE.STOCK_REAL_BACK
     *
     * @mbggenerated
     */
    public String getStockRealBack() {
        return stockRealBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STOCK_REAL_BACK
     *
     * @param stockRealBack the value for HS_USER.STKCODE.STOCK_REAL_BACK
     *
     * @mbggenerated
     */
    public void setStockRealBack(String stockRealBack) {
        this.stockRealBack = stockRealBack == null ? null : stockRealBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MATCH_TYPE
     *
     * @return the value of HS_USER.STKCODE.MATCH_TYPE
     *
     * @mbggenerated
     */
    public String getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MATCH_TYPE
     *
     * @param matchType the value for HS_USER.STKCODE.MATCH_TYPE
     *
     * @mbggenerated
     */
    public void setMatchType(String matchType) {
        this.matchType = matchType == null ? null : matchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.TN_TYPE
     *
     * @return the value of HS_USER.STKCODE.TN_TYPE
     *
     * @mbggenerated
     */
    public String getTnType() {
        return tnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.TN_TYPE
     *
     * @param tnType the value for HS_USER.STKCODE.TN_TYPE
     *
     * @mbggenerated
     */
    public void setTnType(String tnType) {
        this.tnType = tnType == null ? null : tnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.FUND_BACK_N
     *
     * @return the value of HS_USER.STKCODE.FUND_BACK_N
     *
     * @mbggenerated
     */
    public Short getFundBackN() {
        return fundBackN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.FUND_BACK_N
     *
     * @param fundBackN the value for HS_USER.STKCODE.FUND_BACK_N
     *
     * @mbggenerated
     */
    public void setFundBackN(Short fundBackN) {
        this.fundBackN = fundBackN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STOCK_BACK_N
     *
     * @return the value of HS_USER.STKCODE.STOCK_BACK_N
     *
     * @mbggenerated
     */
    public Short getStockBackN() {
        return stockBackN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STOCK_BACK_N
     *
     * @param stockBackN the value for HS_USER.STKCODE.STOCK_BACK_N
     *
     * @mbggenerated
     */
    public void setStockBackN(Short stockBackN) {
        this.stockBackN = stockBackN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.PAR_VALUE
     *
     * @return the value of HS_USER.STKCODE.PAR_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getParValue() {
        return parValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.PAR_VALUE
     *
     * @param parValue the value for HS_USER.STKCODE.PAR_VALUE
     *
     * @mbggenerated
     */
    public void setParValue(BigDecimal parValue) {
        this.parValue = parValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.HOLD_AMOUNT
     *
     * @return the value of HS_USER.STKCODE.HOLD_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getHoldAmount() {
        return holdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.HOLD_AMOUNT
     *
     * @param holdAmount the value for HS_USER.STKCODE.HOLD_AMOUNT
     *
     * @mbggenerated
     */
    public void setHoldAmount(BigDecimal holdAmount) {
        this.holdAmount = holdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MARKET_DATE
     *
     * @return the value of HS_USER.STKCODE.MARKET_DATE
     *
     * @mbggenerated
     */
    public Long getMarketDate() {
        return marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MARKET_DATE
     *
     * @param marketDate the value for HS_USER.STKCODE.MARKET_DATE
     *
     * @mbggenerated
     */
    public void setMarketDate(Long marketDate) {
        this.marketDate = marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.DEFAULTPRICE_TYPE
     *
     * @return the value of HS_USER.STKCODE.DEFAULTPRICE_TYPE
     *
     * @mbggenerated
     */
    public String getDefaultpriceType() {
        return defaultpriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.DEFAULTPRICE_TYPE
     *
     * @param defaultpriceType the value for HS_USER.STKCODE.DEFAULTPRICE_TYPE
     *
     * @mbggenerated
     */
    public void setDefaultpriceType(String defaultpriceType) {
        this.defaultpriceType = defaultpriceType == null ? null : defaultpriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.LIMITPRICE_TYPE
     *
     * @return the value of HS_USER.STKCODE.LIMITPRICE_TYPE
     *
     * @mbggenerated
     */
    public String getLimitpriceType() {
        return limitpriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.LIMITPRICE_TYPE
     *
     * @param limitpriceType the value for HS_USER.STKCODE.LIMITPRICE_TYPE
     *
     * @mbggenerated
     */
    public void setLimitpriceType(String limitpriceType) {
        this.limitpriceType = limitpriceType == null ? null : limitpriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BASEPRICE_TYPE
     *
     * @return the value of HS_USER.STKCODE.BASEPRICE_TYPE
     *
     * @mbggenerated
     */
    public String getBasepriceType() {
        return basepriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BASEPRICE_TYPE
     *
     * @param basepriceType the value for HS_USER.STKCODE.BASEPRICE_TYPE
     *
     * @mbggenerated
     */
    public void setBasepriceType(String basepriceType) {
        this.basepriceType = basepriceType == null ? null : basepriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.LIMIT_VALUE_UP
     *
     * @return the value of HS_USER.STKCODE.LIMIT_VALUE_UP
     *
     * @mbggenerated
     */
    public Long getLimitValueUp() {
        return limitValueUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.LIMIT_VALUE_UP
     *
     * @param limitValueUp the value for HS_USER.STKCODE.LIMIT_VALUE_UP
     *
     * @mbggenerated
     */
    public void setLimitValueUp(Long limitValueUp) {
        this.limitValueUp = limitValueUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.LIMIT_VALUE_LOW
     *
     * @return the value of HS_USER.STKCODE.LIMIT_VALUE_LOW
     *
     * @mbggenerated
     */
    public Long getLimitValueLow() {
        return limitValueLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.LIMIT_VALUE_LOW
     *
     * @param limitValueLow the value for HS_USER.STKCODE.LIMIT_VALUE_LOW
     *
     * @mbggenerated
     */
    public void setLimitValueLow(Long limitValueLow) {
        this.limitValueLow = limitValueLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BUY_CLIENT
     *
     * @return the value of HS_USER.STKCODE.BUY_CLIENT
     *
     * @mbggenerated
     */
    public String getBuyClient() {
        return buyClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BUY_CLIENT
     *
     * @param buyClient the value for HS_USER.STKCODE.BUY_CLIENT
     *
     * @mbggenerated
     */
    public void setBuyClient(String buyClient) {
        this.buyClient = buyClient == null ? null : buyClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.SELL_CLIENT
     *
     * @return the value of HS_USER.STKCODE.SELL_CLIENT
     *
     * @mbggenerated
     */
    public String getSellClient() {
        return sellClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.SELL_CLIENT
     *
     * @param sellClient the value for HS_USER.STKCODE.SELL_CLIENT
     *
     * @mbggenerated
     */
    public void setSellClient(String sellClient) {
        this.sellClient = sellClient == null ? null : sellClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BUY_HOLDER
     *
     * @return the value of HS_USER.STKCODE.BUY_HOLDER
     *
     * @mbggenerated
     */
    public String getBuyHolder() {
        return buyHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BUY_HOLDER
     *
     * @param buyHolder the value for HS_USER.STKCODE.BUY_HOLDER
     *
     * @mbggenerated
     */
    public void setBuyHolder(String buyHolder) {
        this.buyHolder = buyHolder == null ? null : buyHolder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.SELL_HOLDER
     *
     * @return the value of HS_USER.STKCODE.SELL_HOLDER
     *
     * @mbggenerated
     */
    public String getSellHolder() {
        return sellHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.SELL_HOLDER
     *
     * @param sellHolder the value for HS_USER.STKCODE.SELL_HOLDER
     *
     * @mbggenerated
     */
    public void setSellHolder(String sellHolder) {
        this.sellHolder = sellHolder == null ? null : sellHolder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.EN_ENTRUST_WAY
     *
     * @return the value of HS_USER.STKCODE.EN_ENTRUST_WAY
     *
     * @mbggenerated
     */
    public String getEnEntrustWay() {
        return enEntrustWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.EN_ENTRUST_WAY
     *
     * @param enEntrustWay the value for HS_USER.STKCODE.EN_ENTRUST_WAY
     *
     * @mbggenerated
     */
    public void setEnEntrustWay(String enEntrustWay) {
        this.enEntrustWay = enEntrustWay == null ? null : enEntrustWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.ELIG_RISK_LEVEL
     *
     * @return the value of HS_USER.STKCODE.ELIG_RISK_LEVEL
     *
     * @mbggenerated
     */
    public Long getEligRiskLevel() {
        return eligRiskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.ELIG_RISK_LEVEL
     *
     * @param eligRiskLevel the value for HS_USER.STKCODE.ELIG_RISK_LEVEL
     *
     * @mbggenerated
     */
    public void setEligRiskLevel(Long eligRiskLevel) {
        this.eligRiskLevel = eligRiskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.LOW_BALANCE
     *
     * @return the value of HS_USER.STKCODE.LOW_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getLowBalance() {
        return lowBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.LOW_BALANCE
     *
     * @param lowBalance the value for HS_USER.STKCODE.LOW_BALANCE
     *
     * @mbggenerated
     */
    public void setLowBalance(BigDecimal lowBalance) {
        this.lowBalance = lowBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.HIGH_BALANCE
     *
     * @return the value of HS_USER.STKCODE.HIGH_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getHighBalance() {
        return highBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.HIGH_BALANCE
     *
     * @param highBalance the value for HS_USER.STKCODE.HIGH_BALANCE
     *
     * @mbggenerated
     */
    public void setHighBalance(BigDecimal highBalance) {
        this.highBalance = highBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.CANCEL_LOW_BALANCE
     *
     * @return the value of HS_USER.STKCODE.CANCEL_LOW_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getCancelLowBalance() {
        return cancelLowBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.CANCEL_LOW_BALANCE
     *
     * @param cancelLowBalance the value for HS_USER.STKCODE.CANCEL_LOW_BALANCE
     *
     * @mbggenerated
     */
    public void setCancelLowBalance(BigDecimal cancelLowBalance) {
        this.cancelLowBalance = cancelLowBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.CANCEL_HIGH_BALANCE
     *
     * @return the value of HS_USER.STKCODE.CANCEL_HIGH_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getCancelHighBalance() {
        return cancelHighBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.CANCEL_HIGH_BALANCE
     *
     * @param cancelHighBalance the value for HS_USER.STKCODE.CANCEL_HIGH_BALANCE
     *
     * @mbggenerated
     */
    public void setCancelHighBalance(BigDecimal cancelHighBalance) {
        this.cancelHighBalance = cancelHighBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.ISSUE_DATE
     *
     * @return the value of HS_USER.STKCODE.ISSUE_DATE
     *
     * @mbggenerated
     */
    public Long getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.ISSUE_DATE
     *
     * @param issueDate the value for HS_USER.STKCODE.ISSUE_DATE
     *
     * @mbggenerated
     */
    public void setIssueDate(Long issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MODIFY_DATE
     *
     * @return the value of HS_USER.STKCODE.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Long getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MODIFY_DATE
     *
     * @param modifyDate the value for HS_USER.STKCODE.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Long modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.BONDINV_FLAG
     *
     * @return the value of HS_USER.STKCODE.BONDINV_FLAG
     *
     * @mbggenerated
     */
    public String getBondinvFlag() {
        return bondinvFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.BONDINV_FLAG
     *
     * @param bondinvFlag the value for HS_USER.STKCODE.BONDINV_FLAG
     *
     * @mbggenerated
     */
    public void setBondinvFlag(String bondinvFlag) {
        this.bondinvFlag = bondinvFlag == null ? null : bondinvFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.DELIST_FLAG
     *
     * @return the value of HS_USER.STKCODE.DELIST_FLAG
     *
     * @mbggenerated
     */
    public String getDelistFlag() {
        return delistFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.DELIST_FLAG
     *
     * @param delistFlag the value for HS_USER.STKCODE.DELIST_FLAG
     *
     * @mbggenerated
     */
    public void setDelistFlag(String delistFlag) {
        this.delistFlag = delistFlag == null ? null : delistFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.DELIST_DATE
     *
     * @return the value of HS_USER.STKCODE.DELIST_DATE
     *
     * @mbggenerated
     */
    public Long getDelistDate() {
        return delistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.DELIST_DATE
     *
     * @param delistDate the value for HS_USER.STKCODE.DELIST_DATE
     *
     * @mbggenerated
     */
    public void setDelistDate(Long delistDate) {
        this.delistDate = delistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STBTRANS_TYPE
     *
     * @return the value of HS_USER.STKCODE.STBTRANS_TYPE
     *
     * @mbggenerated
     */
    public String getStbtransType() {
        return stbtransType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STBTRANS_TYPE
     *
     * @param stbtransType the value for HS_USER.STKCODE.STBTRANS_TYPE
     *
     * @mbggenerated
     */
    public void setStbtransType(String stbtransType) {
        this.stbtransType = stbtransType == null ? null : stbtransType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.SUB_STOCK_TYPE
     *
     * @return the value of HS_USER.STKCODE.SUB_STOCK_TYPE
     *
     * @mbggenerated
     */
    public String getSubStockType() {
        return subStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.SUB_STOCK_TYPE
     *
     * @param subStockType the value for HS_USER.STKCODE.SUB_STOCK_TYPE
     *
     * @mbggenerated
     */
    public void setSubStockType(String subStockType) {
        this.subStockType = subStockType == null ? null : subStockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STBTRANS_STATUS
     *
     * @return the value of HS_USER.STKCODE.STBTRANS_STATUS
     *
     * @mbggenerated
     */
    public String getStbtransStatus() {
        return stbtransStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STBTRANS_STATUS
     *
     * @param stbtransStatus the value for HS_USER.STKCODE.STBTRANS_STATUS
     *
     * @mbggenerated
     */
    public void setStbtransStatus(String stbtransStatus) {
        this.stbtransStatus = stbtransStatus == null ? null : stbtransStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.STKCODE_CTRLSTR
     *
     * @return the value of HS_USER.STKCODE.STKCODE_CTRLSTR
     *
     * @mbggenerated
     */
    public String getStkcodeCtrlstr() {
        return stkcodeCtrlstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.STKCODE_CTRLSTR
     *
     * @param stkcodeCtrlstr the value for HS_USER.STKCODE.STKCODE_CTRLSTR
     *
     * @mbggenerated
     */
    public void setStkcodeCtrlstr(String stkcodeCtrlstr) {
        this.stkcodeCtrlstr = stkcodeCtrlstr == null ? null : stkcodeCtrlstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.EXDIVIDEND_FLAG
     *
     * @return the value of HS_USER.STKCODE.EXDIVIDEND_FLAG
     *
     * @mbggenerated
     */
    public String getExdividendFlag() {
        return exdividendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.EXDIVIDEND_FLAG
     *
     * @param exdividendFlag the value for HS_USER.STKCODE.EXDIVIDEND_FLAG
     *
     * @mbggenerated
     */
    public void setExdividendFlag(String exdividendFlag) {
        this.exdividendFlag = exdividendFlag == null ? null : exdividendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MARKETMAKER_AMOUNT
     *
     * @return the value of HS_USER.STKCODE.MARKETMAKER_AMOUNT
     *
     * @mbggenerated
     */
    public Long getMarketmakerAmount() {
        return marketmakerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MARKETMAKER_AMOUNT
     *
     * @param marketmakerAmount the value for HS_USER.STKCODE.MARKETMAKER_AMOUNT
     *
     * @mbggenerated
     */
    public void setMarketmakerAmount(Long marketmakerAmount) {
        this.marketmakerAmount = marketmakerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.TRANS_PRICE
     *
     * @return the value of HS_USER.STKCODE.TRANS_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getTransPrice() {
        return transPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.TRANS_PRICE
     *
     * @param transPrice the value for HS_USER.STKCODE.TRANS_PRICE
     *
     * @mbggenerated
     */
    public void setTransPrice(BigDecimal transPrice) {
        this.transPrice = transPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MARKET_HIGH_AMOUNT
     *
     * @return the value of HS_USER.STKCODE.MARKET_HIGH_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getMarketHighAmount() {
        return marketHighAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MARKET_HIGH_AMOUNT
     *
     * @param marketHighAmount the value for HS_USER.STKCODE.MARKET_HIGH_AMOUNT
     *
     * @mbggenerated
     */
    public void setMarketHighAmount(BigDecimal marketHighAmount) {
        this.marketHighAmount = marketHighAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_USER.STKCODE.MARKET_LOW_AMOUNT
     *
     * @return the value of HS_USER.STKCODE.MARKET_LOW_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getMarketLowAmount() {
        return marketLowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_USER.STKCODE.MARKET_LOW_AMOUNT
     *
     * @param marketLowAmount the value for HS_USER.STKCODE.MARKET_LOW_AMOUNT
     *
     * @mbggenerated
     */
    public void setMarketLowAmount(BigDecimal marketLowAmount) {
        this.marketLowAmount = marketLowAmount;
    }
}