package com.paul.base.sync.oracle.asset.model;

public class FundAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.BRANCH_NO
     *
     * @mbggenerated
     */
    private Long branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.CLIENT_ID
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.FUND_ACCOUNT
     *
     * @mbggenerated
     */
    private String fundAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.FUND_CARD
     *
     * @mbggenerated
     */
    private String fundCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.MAIN_FLAG
     *
     * @mbggenerated
     */
    private String mainFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.RISK_LEVEL
     *
     * @mbggenerated
     */
    private Long riskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.RISK_ENDDATE
     *
     * @mbggenerated
     */
    private Long riskEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.INTER_ACCOUNT
     *
     * @mbggenerated
     */
    private String interAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.CLIENT_GROUP
     *
     * @mbggenerated
     */
    private Long clientGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.ROOM_CODE
     *
     * @mbggenerated
     */
    private Long roomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.ASSET_PROP
     *
     * @mbggenerated
     */
    private String assetProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.FARE_KIND_STR
     *
     * @mbggenerated
     */
    private String fareKindStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.DISCOUNT_MODEL
     *
     * @mbggenerated
     */
    private Long discountModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.EN_ENTRUST_WAY
     *
     * @mbggenerated
     */
    private String enEntrustWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.CLIENT_RIGHTS
     *
     * @mbggenerated
     */
    private String clientRights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.RESTRICTION
     *
     * @mbggenerated
     */
    private String restriction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.PROFIT_FLAG
     *
     * @mbggenerated
     */
    private String profitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.OPEN_DATE
     *
     * @mbggenerated
     */
    private Long openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.CANCEL_DATE
     *
     * @mbggenerated
     */
    private Long cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.PRODUCT_FLAG
     *
     * @mbggenerated
     */
    private String productFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.FUNDACCT_STATUS
     *
     * @mbggenerated
     */
    private String fundacctStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.LIMIT_FLAG
     *
     * @mbggenerated
     */
    private Long limitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_ASSET.FUNDACCOUNT.POSITION_STR
     *
     * @mbggenerated
     */
    private String positionStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.BRANCH_NO
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.BRANCH_NO
     *
     * @param branchNo the value for HS_ASSET.FUNDACCOUNT.BRANCH_NO
     *
     * @mbggenerated
     */
    public void setBranchNo(Long branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.CLIENT_ID
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.CLIENT_ID
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.CLIENT_ID
     *
     * @param clientId the value for HS_ASSET.FUNDACCOUNT.CLIENT_ID
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.FUND_ACCOUNT
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.FUND_ACCOUNT
     *
     * @mbggenerated
     */
    public String getFundAccount() {
        return fundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.FUND_ACCOUNT
     *
     * @param fundAccount the value for HS_ASSET.FUNDACCOUNT.FUND_ACCOUNT
     *
     * @mbggenerated
     */
    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount == null ? null : fundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.FUND_CARD
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.FUND_CARD
     *
     * @mbggenerated
     */
    public String getFundCard() {
        return fundCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.FUND_CARD
     *
     * @param fundCard the value for HS_ASSET.FUNDACCOUNT.FUND_CARD
     *
     * @mbggenerated
     */
    public void setFundCard(String fundCard) {
        this.fundCard = fundCard == null ? null : fundCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.MAIN_FLAG
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.MAIN_FLAG
     *
     * @mbggenerated
     */
    public String getMainFlag() {
        return mainFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.MAIN_FLAG
     *
     * @param mainFlag the value for HS_ASSET.FUNDACCOUNT.MAIN_FLAG
     *
     * @mbggenerated
     */
    public void setMainFlag(String mainFlag) {
        this.mainFlag = mainFlag == null ? null : mainFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.RISK_LEVEL
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.RISK_LEVEL
     *
     * @mbggenerated
     */
    public Long getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.RISK_LEVEL
     *
     * @param riskLevel the value for HS_ASSET.FUNDACCOUNT.RISK_LEVEL
     *
     * @mbggenerated
     */
    public void setRiskLevel(Long riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.RISK_ENDDATE
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.RISK_ENDDATE
     *
     * @mbggenerated
     */
    public Long getRiskEnddate() {
        return riskEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.RISK_ENDDATE
     *
     * @param riskEnddate the value for HS_ASSET.FUNDACCOUNT.RISK_ENDDATE
     *
     * @mbggenerated
     */
    public void setRiskEnddate(Long riskEnddate) {
        this.riskEnddate = riskEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.INTER_ACCOUNT
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.INTER_ACCOUNT
     *
     * @mbggenerated
     */
    public String getInterAccount() {
        return interAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.INTER_ACCOUNT
     *
     * @param interAccount the value for HS_ASSET.FUNDACCOUNT.INTER_ACCOUNT
     *
     * @mbggenerated
     */
    public void setInterAccount(String interAccount) {
        this.interAccount = interAccount == null ? null : interAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.CLIENT_GROUP
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.CLIENT_GROUP
     *
     * @mbggenerated
     */
    public Long getClientGroup() {
        return clientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.CLIENT_GROUP
     *
     * @param clientGroup the value for HS_ASSET.FUNDACCOUNT.CLIENT_GROUP
     *
     * @mbggenerated
     */
    public void setClientGroup(Long clientGroup) {
        this.clientGroup = clientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.ROOM_CODE
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.ROOM_CODE
     *
     * @mbggenerated
     */
    public Long getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.ROOM_CODE
     *
     * @param roomCode the value for HS_ASSET.FUNDACCOUNT.ROOM_CODE
     *
     * @mbggenerated
     */
    public void setRoomCode(Long roomCode) {
        this.roomCode = roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.ASSET_PROP
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.ASSET_PROP
     *
     * @mbggenerated
     */
    public String getAssetProp() {
        return assetProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.ASSET_PROP
     *
     * @param assetProp the value for HS_ASSET.FUNDACCOUNT.ASSET_PROP
     *
     * @mbggenerated
     */
    public void setAssetProp(String assetProp) {
        this.assetProp = assetProp == null ? null : assetProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.FARE_KIND_STR
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.FARE_KIND_STR
     *
     * @mbggenerated
     */
    public String getFareKindStr() {
        return fareKindStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.FARE_KIND_STR
     *
     * @param fareKindStr the value for HS_ASSET.FUNDACCOUNT.FARE_KIND_STR
     *
     * @mbggenerated
     */
    public void setFareKindStr(String fareKindStr) {
        this.fareKindStr = fareKindStr == null ? null : fareKindStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.DISCOUNT_MODEL
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.DISCOUNT_MODEL
     *
     * @mbggenerated
     */
    public Long getDiscountModel() {
        return discountModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.DISCOUNT_MODEL
     *
     * @param discountModel the value for HS_ASSET.FUNDACCOUNT.DISCOUNT_MODEL
     *
     * @mbggenerated
     */
    public void setDiscountModel(Long discountModel) {
        this.discountModel = discountModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.EN_ENTRUST_WAY
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.EN_ENTRUST_WAY
     *
     * @mbggenerated
     */
    public String getEnEntrustWay() {
        return enEntrustWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.EN_ENTRUST_WAY
     *
     * @param enEntrustWay the value for HS_ASSET.FUNDACCOUNT.EN_ENTRUST_WAY
     *
     * @mbggenerated
     */
    public void setEnEntrustWay(String enEntrustWay) {
        this.enEntrustWay = enEntrustWay == null ? null : enEntrustWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.CLIENT_RIGHTS
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.CLIENT_RIGHTS
     *
     * @mbggenerated
     */
    public String getClientRights() {
        return clientRights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.CLIENT_RIGHTS
     *
     * @param clientRights the value for HS_ASSET.FUNDACCOUNT.CLIENT_RIGHTS
     *
     * @mbggenerated
     */
    public void setClientRights(String clientRights) {
        this.clientRights = clientRights == null ? null : clientRights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.RESTRICTION
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.RESTRICTION
     *
     * @mbggenerated
     */
    public String getRestriction() {
        return restriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.RESTRICTION
     *
     * @param restriction the value for HS_ASSET.FUNDACCOUNT.RESTRICTION
     *
     * @mbggenerated
     */
    public void setRestriction(String restriction) {
        this.restriction = restriction == null ? null : restriction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.PROFIT_FLAG
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.PROFIT_FLAG
     *
     * @mbggenerated
     */
    public String getProfitFlag() {
        return profitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.PROFIT_FLAG
     *
     * @param profitFlag the value for HS_ASSET.FUNDACCOUNT.PROFIT_FLAG
     *
     * @mbggenerated
     */
    public void setProfitFlag(String profitFlag) {
        this.profitFlag = profitFlag == null ? null : profitFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.OPEN_DATE
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.OPEN_DATE
     *
     * @mbggenerated
     */
    public Long getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.OPEN_DATE
     *
     * @param openDate the value for HS_ASSET.FUNDACCOUNT.OPEN_DATE
     *
     * @mbggenerated
     */
    public void setOpenDate(Long openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.CANCEL_DATE
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.CANCEL_DATE
     *
     * @mbggenerated
     */
    public Long getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.CANCEL_DATE
     *
     * @param cancelDate the value for HS_ASSET.FUNDACCOUNT.CANCEL_DATE
     *
     * @mbggenerated
     */
    public void setCancelDate(Long cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.PRODUCT_FLAG
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.PRODUCT_FLAG
     *
     * @mbggenerated
     */
    public String getProductFlag() {
        return productFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.PRODUCT_FLAG
     *
     * @param productFlag the value for HS_ASSET.FUNDACCOUNT.PRODUCT_FLAG
     *
     * @mbggenerated
     */
    public void setProductFlag(String productFlag) {
        this.productFlag = productFlag == null ? null : productFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.FUNDACCT_STATUS
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.FUNDACCT_STATUS
     *
     * @mbggenerated
     */
    public String getFundacctStatus() {
        return fundacctStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.FUNDACCT_STATUS
     *
     * @param fundacctStatus the value for HS_ASSET.FUNDACCOUNT.FUNDACCT_STATUS
     *
     * @mbggenerated
     */
    public void setFundacctStatus(String fundacctStatus) {
        this.fundacctStatus = fundacctStatus == null ? null : fundacctStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.LIMIT_FLAG
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.LIMIT_FLAG
     *
     * @mbggenerated
     */
    public Long getLimitFlag() {
        return limitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.LIMIT_FLAG
     *
     * @param limitFlag the value for HS_ASSET.FUNDACCOUNT.LIMIT_FLAG
     *
     * @mbggenerated
     */
    public void setLimitFlag(Long limitFlag) {
        this.limitFlag = limitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.REMARK
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.REMARK
     *
     * @param remark the value for HS_ASSET.FUNDACCOUNT.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_ASSET.FUNDACCOUNT.POSITION_STR
     *
     * @return the value of HS_ASSET.FUNDACCOUNT.POSITION_STR
     *
     * @mbggenerated
     */
    public String getPositionStr() {
        return positionStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_ASSET.FUNDACCOUNT.POSITION_STR
     *
     * @param positionStr the value for HS_ASSET.FUNDACCOUNT.POSITION_STR
     *
     * @mbggenerated
     */
    public void setPositionStr(String positionStr) {
        this.positionStr = positionStr == null ? null : positionStr.trim();
    }
}