package com.paul.base.sync.oracle.secu.model;

import java.math.BigDecimal;

public class Entrust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.INIT_DATE
     *
     * @mbggenerated
     */
    private Long initDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.CURR_DATE
     *
     * @mbggenerated
     */
    private Long currDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.CURR_TIME
     *
     * @mbggenerated
     */
    private Long currTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_NO
     *
     * @mbggenerated
     */
    private Long entrustNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.OP_BRANCH_NO
     *
     * @mbggenerated
     */
    private Long opBranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.OPERATOR_NO
     *
     * @mbggenerated
     */
    private String operatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.OP_ENTRUST_WAY
     *
     * @mbggenerated
     */
    private String opEntrustWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.OP_STATION
     *
     * @mbggenerated
     */
    private String opStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.BATCH_NO
     *
     * @mbggenerated
     */
    private Long batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.BRANCH_NO
     *
     * @mbggenerated
     */
    private Long branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.FUND_ACCOUNT
     *
     * @mbggenerated
     */
    private String fundAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.CLIENT_ID
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    private String exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.STOCK_ACCOUNT
     *
     * @mbggenerated
     */
    private String stockAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.REPORT_ACCOUNT
     *
     * @mbggenerated
     */
    private String reportAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.SEAT_NO
     *
     * @mbggenerated
     */
    private String seatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.STOCK_CODE
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.STOCK_TYPE
     *
     * @mbggenerated
     */
    private String stockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_BS
     *
     * @mbggenerated
     */
    private String entrustBs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal entrustAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal entrustPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_TYPE
     *
     * @mbggenerated
     */
    private String entrustType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_PROP
     *
     * @mbggenerated
     */
    private String entrustProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.REPORT_TIME
     *
     * @mbggenerated
     */
    private Long reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.REPORT_NO
     *
     * @mbggenerated
     */
    private Long reportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.RECORD_NO
     *
     * @mbggenerated
     */
    private Long recordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.BUSINESS_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal businessAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.WITHDRAW_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal withdrawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.BUSINESS_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal businessPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.BUSINESS_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal businessBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.CLEAR_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal clearBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.PREV_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal prevBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.REPORT_BS
     *
     * @mbggenerated
     */
    private String reportBs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.STORE_UNIT
     *
     * @mbggenerated
     */
    private Long storeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.REPORT_UNIT
     *
     * @mbggenerated
     */
    private Long reportUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ERROR_NO
     *
     * @mbggenerated
     */
    private Long errorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ENTRUST_STATUS
     *
     * @mbggenerated
     */
    private String entrustStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.MONEY_TYPE
     *
     * @mbggenerated
     */
    private String moneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.CLIENT_GROUP
     *
     * @mbggenerated
     */
    private Long clientGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ROOM_CODE
     *
     * @mbggenerated
     */
    private Long roomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.CANCEL_SERIALNO
     *
     * @mbggenerated
     */
    private String cancelSerialno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.FARE_KIND
     *
     * @mbggenerated
     */
    private Long fareKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.POSITION_STR
     *
     * @mbggenerated
     */
    private String positionStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.LOGIN_PBU
     *
     * @mbggenerated
     */
    private String loginPbu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ORDER_ID
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.ORIG_ORDER_ID
     *
     * @mbggenerated
     */
    private String origOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.EXT_ORDER_ID
     *
     * @mbggenerated
     */
    private String extOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_SECU.ENTRUST.SUB_STOCK_TYPE
     *
     * @mbggenerated
     */
    private String subStockType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.INIT_DATE
     *
     * @return the value of HS_SECU.ENTRUST.INIT_DATE
     *
     * @mbggenerated
     */
    public Long getInitDate() {
        return initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.INIT_DATE
     *
     * @param initDate the value for HS_SECU.ENTRUST.INIT_DATE
     *
     * @mbggenerated
     */
    public void setInitDate(Long initDate) {
        this.initDate = initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.CURR_DATE
     *
     * @return the value of HS_SECU.ENTRUST.CURR_DATE
     *
     * @mbggenerated
     */
    public Long getCurrDate() {
        return currDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.CURR_DATE
     *
     * @param currDate the value for HS_SECU.ENTRUST.CURR_DATE
     *
     * @mbggenerated
     */
    public void setCurrDate(Long currDate) {
        this.currDate = currDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.CURR_TIME
     *
     * @return the value of HS_SECU.ENTRUST.CURR_TIME
     *
     * @mbggenerated
     */
    public Long getCurrTime() {
        return currTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.CURR_TIME
     *
     * @param currTime the value for HS_SECU.ENTRUST.CURR_TIME
     *
     * @mbggenerated
     */
    public void setCurrTime(Long currTime) {
        this.currTime = currTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_NO
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_NO
     *
     * @mbggenerated
     */
    public Long getEntrustNo() {
        return entrustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_NO
     *
     * @param entrustNo the value for HS_SECU.ENTRUST.ENTRUST_NO
     *
     * @mbggenerated
     */
    public void setEntrustNo(Long entrustNo) {
        this.entrustNo = entrustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.OP_BRANCH_NO
     *
     * @return the value of HS_SECU.ENTRUST.OP_BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getOpBranchNo() {
        return opBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.OP_BRANCH_NO
     *
     * @param opBranchNo the value for HS_SECU.ENTRUST.OP_BRANCH_NO
     *
     * @mbggenerated
     */
    public void setOpBranchNo(Long opBranchNo) {
        this.opBranchNo = opBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.OPERATOR_NO
     *
     * @return the value of HS_SECU.ENTRUST.OPERATOR_NO
     *
     * @mbggenerated
     */
    public String getOperatorNo() {
        return operatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.OPERATOR_NO
     *
     * @param operatorNo the value for HS_SECU.ENTRUST.OPERATOR_NO
     *
     * @mbggenerated
     */
    public void setOperatorNo(String operatorNo) {
        this.operatorNo = operatorNo == null ? null : operatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.OP_ENTRUST_WAY
     *
     * @return the value of HS_SECU.ENTRUST.OP_ENTRUST_WAY
     *
     * @mbggenerated
     */
    public String getOpEntrustWay() {
        return opEntrustWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.OP_ENTRUST_WAY
     *
     * @param opEntrustWay the value for HS_SECU.ENTRUST.OP_ENTRUST_WAY
     *
     * @mbggenerated
     */
    public void setOpEntrustWay(String opEntrustWay) {
        this.opEntrustWay = opEntrustWay == null ? null : opEntrustWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.OP_STATION
     *
     * @return the value of HS_SECU.ENTRUST.OP_STATION
     *
     * @mbggenerated
     */
    public String getOpStation() {
        return opStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.OP_STATION
     *
     * @param opStation the value for HS_SECU.ENTRUST.OP_STATION
     *
     * @mbggenerated
     */
    public void setOpStation(String opStation) {
        this.opStation = opStation == null ? null : opStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.BATCH_NO
     *
     * @return the value of HS_SECU.ENTRUST.BATCH_NO
     *
     * @mbggenerated
     */
    public Long getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.BATCH_NO
     *
     * @param batchNo the value for HS_SECU.ENTRUST.BATCH_NO
     *
     * @mbggenerated
     */
    public void setBatchNo(Long batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.BRANCH_NO
     *
     * @return the value of HS_SECU.ENTRUST.BRANCH_NO
     *
     * @mbggenerated
     */
    public Long getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.BRANCH_NO
     *
     * @param branchNo the value for HS_SECU.ENTRUST.BRANCH_NO
     *
     * @mbggenerated
     */
    public void setBranchNo(Long branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.FUND_ACCOUNT
     *
     * @return the value of HS_SECU.ENTRUST.FUND_ACCOUNT
     *
     * @mbggenerated
     */
    public String getFundAccount() {
        return fundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.FUND_ACCOUNT
     *
     * @param fundAccount the value for HS_SECU.ENTRUST.FUND_ACCOUNT
     *
     * @mbggenerated
     */
    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount == null ? null : fundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.CLIENT_ID
     *
     * @return the value of HS_SECU.ENTRUST.CLIENT_ID
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.CLIENT_ID
     *
     * @param clientId the value for HS_SECU.ENTRUST.CLIENT_ID
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.EXCHANGE_TYPE
     *
     * @return the value of HS_SECU.ENTRUST.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public String getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.EXCHANGE_TYPE
     *
     * @param exchangeType the value for HS_SECU.ENTRUST.EXCHANGE_TYPE
     *
     * @mbggenerated
     */
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType == null ? null : exchangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.STOCK_ACCOUNT
     *
     * @return the value of HS_SECU.ENTRUST.STOCK_ACCOUNT
     *
     * @mbggenerated
     */
    public String getStockAccount() {
        return stockAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.STOCK_ACCOUNT
     *
     * @param stockAccount the value for HS_SECU.ENTRUST.STOCK_ACCOUNT
     *
     * @mbggenerated
     */
    public void setStockAccount(String stockAccount) {
        this.stockAccount = stockAccount == null ? null : stockAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.REPORT_ACCOUNT
     *
     * @return the value of HS_SECU.ENTRUST.REPORT_ACCOUNT
     *
     * @mbggenerated
     */
    public String getReportAccount() {
        return reportAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.REPORT_ACCOUNT
     *
     * @param reportAccount the value for HS_SECU.ENTRUST.REPORT_ACCOUNT
     *
     * @mbggenerated
     */
    public void setReportAccount(String reportAccount) {
        this.reportAccount = reportAccount == null ? null : reportAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.SEAT_NO
     *
     * @return the value of HS_SECU.ENTRUST.SEAT_NO
     *
     * @mbggenerated
     */
    public String getSeatNo() {
        return seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.SEAT_NO
     *
     * @param seatNo the value for HS_SECU.ENTRUST.SEAT_NO
     *
     * @mbggenerated
     */
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo == null ? null : seatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.STOCK_CODE
     *
     * @return the value of HS_SECU.ENTRUST.STOCK_CODE
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.STOCK_CODE
     *
     * @param stockCode the value for HS_SECU.ENTRUST.STOCK_CODE
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.STOCK_TYPE
     *
     * @return the value of HS_SECU.ENTRUST.STOCK_TYPE
     *
     * @mbggenerated
     */
    public String getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.STOCK_TYPE
     *
     * @param stockType the value for HS_SECU.ENTRUST.STOCK_TYPE
     *
     * @mbggenerated
     */
    public void setStockType(String stockType) {
        this.stockType = stockType == null ? null : stockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_BS
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_BS
     *
     * @mbggenerated
     */
    public String getEntrustBs() {
        return entrustBs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_BS
     *
     * @param entrustBs the value for HS_SECU.ENTRUST.ENTRUST_BS
     *
     * @mbggenerated
     */
    public void setEntrustBs(String entrustBs) {
        this.entrustBs = entrustBs == null ? null : entrustBs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_AMOUNT
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getEntrustAmount() {
        return entrustAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_AMOUNT
     *
     * @param entrustAmount the value for HS_SECU.ENTRUST.ENTRUST_AMOUNT
     *
     * @mbggenerated
     */
    public void setEntrustAmount(BigDecimal entrustAmount) {
        this.entrustAmount = entrustAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_PRICE
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getEntrustPrice() {
        return entrustPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_PRICE
     *
     * @param entrustPrice the value for HS_SECU.ENTRUST.ENTRUST_PRICE
     *
     * @mbggenerated
     */
    public void setEntrustPrice(BigDecimal entrustPrice) {
        this.entrustPrice = entrustPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_TYPE
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_TYPE
     *
     * @mbggenerated
     */
    public String getEntrustType() {
        return entrustType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_TYPE
     *
     * @param entrustType the value for HS_SECU.ENTRUST.ENTRUST_TYPE
     *
     * @mbggenerated
     */
    public void setEntrustType(String entrustType) {
        this.entrustType = entrustType == null ? null : entrustType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_PROP
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_PROP
     *
     * @mbggenerated
     */
    public String getEntrustProp() {
        return entrustProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_PROP
     *
     * @param entrustProp the value for HS_SECU.ENTRUST.ENTRUST_PROP
     *
     * @mbggenerated
     */
    public void setEntrustProp(String entrustProp) {
        this.entrustProp = entrustProp == null ? null : entrustProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.REPORT_TIME
     *
     * @return the value of HS_SECU.ENTRUST.REPORT_TIME
     *
     * @mbggenerated
     */
    public Long getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.REPORT_TIME
     *
     * @param reportTime the value for HS_SECU.ENTRUST.REPORT_TIME
     *
     * @mbggenerated
     */
    public void setReportTime(Long reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.REPORT_NO
     *
     * @return the value of HS_SECU.ENTRUST.REPORT_NO
     *
     * @mbggenerated
     */
    public Long getReportNo() {
        return reportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.REPORT_NO
     *
     * @param reportNo the value for HS_SECU.ENTRUST.REPORT_NO
     *
     * @mbggenerated
     */
    public void setReportNo(Long reportNo) {
        this.reportNo = reportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.RECORD_NO
     *
     * @return the value of HS_SECU.ENTRUST.RECORD_NO
     *
     * @mbggenerated
     */
    public Long getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.RECORD_NO
     *
     * @param recordNo the value for HS_SECU.ENTRUST.RECORD_NO
     *
     * @mbggenerated
     */
    public void setRecordNo(Long recordNo) {
        this.recordNo = recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.BUSINESS_AMOUNT
     *
     * @return the value of HS_SECU.ENTRUST.BUSINESS_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getBusinessAmount() {
        return businessAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.BUSINESS_AMOUNT
     *
     * @param businessAmount the value for HS_SECU.ENTRUST.BUSINESS_AMOUNT
     *
     * @mbggenerated
     */
    public void setBusinessAmount(BigDecimal businessAmount) {
        this.businessAmount = businessAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.WITHDRAW_AMOUNT
     *
     * @return the value of HS_SECU.ENTRUST.WITHDRAW_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getWithdrawAmount() {
        return withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.WITHDRAW_AMOUNT
     *
     * @param withdrawAmount the value for HS_SECU.ENTRUST.WITHDRAW_AMOUNT
     *
     * @mbggenerated
     */
    public void setWithdrawAmount(BigDecimal withdrawAmount) {
        this.withdrawAmount = withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.BUSINESS_PRICE
     *
     * @return the value of HS_SECU.ENTRUST.BUSINESS_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getBusinessPrice() {
        return businessPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.BUSINESS_PRICE
     *
     * @param businessPrice the value for HS_SECU.ENTRUST.BUSINESS_PRICE
     *
     * @mbggenerated
     */
    public void setBusinessPrice(BigDecimal businessPrice) {
        this.businessPrice = businessPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.BUSINESS_BALANCE
     *
     * @return the value of HS_SECU.ENTRUST.BUSINESS_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getBusinessBalance() {
        return businessBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.BUSINESS_BALANCE
     *
     * @param businessBalance the value for HS_SECU.ENTRUST.BUSINESS_BALANCE
     *
     * @mbggenerated
     */
    public void setBusinessBalance(BigDecimal businessBalance) {
        this.businessBalance = businessBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.CLEAR_BALANCE
     *
     * @return the value of HS_SECU.ENTRUST.CLEAR_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getClearBalance() {
        return clearBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.CLEAR_BALANCE
     *
     * @param clearBalance the value for HS_SECU.ENTRUST.CLEAR_BALANCE
     *
     * @mbggenerated
     */
    public void setClearBalance(BigDecimal clearBalance) {
        this.clearBalance = clearBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.PREV_BALANCE
     *
     * @return the value of HS_SECU.ENTRUST.PREV_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getPrevBalance() {
        return prevBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.PREV_BALANCE
     *
     * @param prevBalance the value for HS_SECU.ENTRUST.PREV_BALANCE
     *
     * @mbggenerated
     */
    public void setPrevBalance(BigDecimal prevBalance) {
        this.prevBalance = prevBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.REPORT_BS
     *
     * @return the value of HS_SECU.ENTRUST.REPORT_BS
     *
     * @mbggenerated
     */
    public String getReportBs() {
        return reportBs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.REPORT_BS
     *
     * @param reportBs the value for HS_SECU.ENTRUST.REPORT_BS
     *
     * @mbggenerated
     */
    public void setReportBs(String reportBs) {
        this.reportBs = reportBs == null ? null : reportBs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.STORE_UNIT
     *
     * @return the value of HS_SECU.ENTRUST.STORE_UNIT
     *
     * @mbggenerated
     */
    public Long getStoreUnit() {
        return storeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.STORE_UNIT
     *
     * @param storeUnit the value for HS_SECU.ENTRUST.STORE_UNIT
     *
     * @mbggenerated
     */
    public void setStoreUnit(Long storeUnit) {
        this.storeUnit = storeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.REPORT_UNIT
     *
     * @return the value of HS_SECU.ENTRUST.REPORT_UNIT
     *
     * @mbggenerated
     */
    public Long getReportUnit() {
        return reportUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.REPORT_UNIT
     *
     * @param reportUnit the value for HS_SECU.ENTRUST.REPORT_UNIT
     *
     * @mbggenerated
     */
    public void setReportUnit(Long reportUnit) {
        this.reportUnit = reportUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ERROR_NO
     *
     * @return the value of HS_SECU.ENTRUST.ERROR_NO
     *
     * @mbggenerated
     */
    public Long getErrorNo() {
        return errorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ERROR_NO
     *
     * @param errorNo the value for HS_SECU.ENTRUST.ERROR_NO
     *
     * @mbggenerated
     */
    public void setErrorNo(Long errorNo) {
        this.errorNo = errorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ENTRUST_STATUS
     *
     * @return the value of HS_SECU.ENTRUST.ENTRUST_STATUS
     *
     * @mbggenerated
     */
    public String getEntrustStatus() {
        return entrustStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ENTRUST_STATUS
     *
     * @param entrustStatus the value for HS_SECU.ENTRUST.ENTRUST_STATUS
     *
     * @mbggenerated
     */
    public void setEntrustStatus(String entrustStatus) {
        this.entrustStatus = entrustStatus == null ? null : entrustStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.MONEY_TYPE
     *
     * @return the value of HS_SECU.ENTRUST.MONEY_TYPE
     *
     * @mbggenerated
     */
    public String getMoneyType() {
        return moneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.MONEY_TYPE
     *
     * @param moneyType the value for HS_SECU.ENTRUST.MONEY_TYPE
     *
     * @mbggenerated
     */
    public void setMoneyType(String moneyType) {
        this.moneyType = moneyType == null ? null : moneyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.CLIENT_GROUP
     *
     * @return the value of HS_SECU.ENTRUST.CLIENT_GROUP
     *
     * @mbggenerated
     */
    public Long getClientGroup() {
        return clientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.CLIENT_GROUP
     *
     * @param clientGroup the value for HS_SECU.ENTRUST.CLIENT_GROUP
     *
     * @mbggenerated
     */
    public void setClientGroup(Long clientGroup) {
        this.clientGroup = clientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ROOM_CODE
     *
     * @return the value of HS_SECU.ENTRUST.ROOM_CODE
     *
     * @mbggenerated
     */
    public Long getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ROOM_CODE
     *
     * @param roomCode the value for HS_SECU.ENTRUST.ROOM_CODE
     *
     * @mbggenerated
     */
    public void setRoomCode(Long roomCode) {
        this.roomCode = roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.CANCEL_SERIALNO
     *
     * @return the value of HS_SECU.ENTRUST.CANCEL_SERIALNO
     *
     * @mbggenerated
     */
    public String getCancelSerialno() {
        return cancelSerialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.CANCEL_SERIALNO
     *
     * @param cancelSerialno the value for HS_SECU.ENTRUST.CANCEL_SERIALNO
     *
     * @mbggenerated
     */
    public void setCancelSerialno(String cancelSerialno) {
        this.cancelSerialno = cancelSerialno == null ? null : cancelSerialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.FARE_KIND
     *
     * @return the value of HS_SECU.ENTRUST.FARE_KIND
     *
     * @mbggenerated
     */
    public Long getFareKind() {
        return fareKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.FARE_KIND
     *
     * @param fareKind the value for HS_SECU.ENTRUST.FARE_KIND
     *
     * @mbggenerated
     */
    public void setFareKind(Long fareKind) {
        this.fareKind = fareKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.POSITION_STR
     *
     * @return the value of HS_SECU.ENTRUST.POSITION_STR
     *
     * @mbggenerated
     */
    public String getPositionStr() {
        return positionStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.POSITION_STR
     *
     * @param positionStr the value for HS_SECU.ENTRUST.POSITION_STR
     *
     * @mbggenerated
     */
    public void setPositionStr(String positionStr) {
        this.positionStr = positionStr == null ? null : positionStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.LOGIN_PBU
     *
     * @return the value of HS_SECU.ENTRUST.LOGIN_PBU
     *
     * @mbggenerated
     */
    public String getLoginPbu() {
        return loginPbu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.LOGIN_PBU
     *
     * @param loginPbu the value for HS_SECU.ENTRUST.LOGIN_PBU
     *
     * @mbggenerated
     */
    public void setLoginPbu(String loginPbu) {
        this.loginPbu = loginPbu == null ? null : loginPbu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ORDER_ID
     *
     * @return the value of HS_SECU.ENTRUST.ORDER_ID
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ORDER_ID
     *
     * @param orderId the value for HS_SECU.ENTRUST.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.ORIG_ORDER_ID
     *
     * @return the value of HS_SECU.ENTRUST.ORIG_ORDER_ID
     *
     * @mbggenerated
     */
    public String getOrigOrderId() {
        return origOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.ORIG_ORDER_ID
     *
     * @param origOrderId the value for HS_SECU.ENTRUST.ORIG_ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrigOrderId(String origOrderId) {
        this.origOrderId = origOrderId == null ? null : origOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.EXT_ORDER_ID
     *
     * @return the value of HS_SECU.ENTRUST.EXT_ORDER_ID
     *
     * @mbggenerated
     */
    public String getExtOrderId() {
        return extOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.EXT_ORDER_ID
     *
     * @param extOrderId the value for HS_SECU.ENTRUST.EXT_ORDER_ID
     *
     * @mbggenerated
     */
    public void setExtOrderId(String extOrderId) {
        this.extOrderId = extOrderId == null ? null : extOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_SECU.ENTRUST.SUB_STOCK_TYPE
     *
     * @return the value of HS_SECU.ENTRUST.SUB_STOCK_TYPE
     *
     * @mbggenerated
     */
    public String getSubStockType() {
        return subStockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_SECU.ENTRUST.SUB_STOCK_TYPE
     *
     * @param subStockType the value for HS_SECU.ENTRUST.SUB_STOCK_TYPE
     *
     * @mbggenerated
     */
    public void setSubStockType(String subStockType) {
        this.subStockType = subStockType == null ? null : subStockType.trim();
    }
}